name: kafka-basic

services:
  producer:
    container_name: producer
    hostname: producer
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGET_DIR=producer
    depends_on:
      - consumer
    ports:
      - 8080:8080
    networks:
      - hadoop_network

  consumer:
    container_name: consumer
    hostname: consumer
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGET_DIR=consumer
    ports:
      - 8082:8080
    networks:
      - hadoop_network

networks:
  hadoop_network:
    name: hadoop_network
    external: true